server:
  port: 8097

spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
    static-path-pattern: /resources/**

ballRemaining: 24
runsRequired: 40
wicketRemaining: 3
battingTeam: LengaBuru
ballingTeam: Enchai

data:
 description: Data from YAML File
 
 lengaBuru: 
  - playerName: Kirat Boli
    scoringMap:
      "[-1]": 5
      "[0]": 5
      "[1]": 30
      "[2]": 25
      "[3]": 10
      "[4]": 15
      "[5]": 1
      "[6]": 9
          
  - playerName: NS Nodhi
    scoringMap:
      "[-1]": 10
      "[0]": 10
      "[1]": 40
      "[2]": 20
      "[3]": 5
      "[4]": 10
      "[5]": 1
      "[6]": 4
      
  - playerName: R Rumrah
    scoringMap:
      "[-1]": 20
      "[0]": 20
      "[1]": 30
      "[2]": 15
      "[3]": 5
      "[4]": 5
      "[5]": 1
      "[6]": 4
      
  - playerName: Shashi Henra
    scoringMap:
      "[-1]": 30
      "[0]": 30
      "[1]": 25
      "[2]": 5
      "[3]": 0
      "[4]": 5
      "[5]": 1
      "[6]": 4
  
  
 drawLengaBuru: 
  - playerName: Kirat Boli
    scoringMap:
      "[-1]": 5
      "[0]": 5
      "[1]": 30
      "[2]": 25
      "[3]": 10
      "[4]": 15
      "[5]": 1
      "[6]": 9
          
  - playerName: NS Nodhi
    scoringMap:
      "[-1]": 10
      "[0]": 10
      "[1]": 40
      "[2]": 20
      "[3]": 5
      "[4]": 10
      "[5]": 1
      "[6]": 4
 
  
  
 enchaidraw:
  - playerName:  ab de villiers
    scoringMap:
      "[-1]": 20
      "[0]": 20
      "[1]": 30
      "[2]": 15
      "[3]": 5
      "[4]": 5
      "[5]": 1
      "[6]": 4
      
  - playerName: Bc Bopara
    scoringMap:
      "[-1]": 30
      "[0]": 30
      "[1]": 25
      "[2]": 5
      "[3]": 0
      "[4]": 5
      "[5]": 1
      "[6]": 4
